### PR TITLE
Test

### PR DESCRIPTION
**Pull request by Audrey-me**
had to reduce the files into small chunks of commit to enable pushing

### CODE REVIEW

**Comment by Audrey-me** [comment]
my github username is @audrey2001

**Comment by Audrey-me** [comment]
i finally was able to deploy my changes to enable visuals, that is the link below 
https://my-changes.netlify.app/

**Comment by Thuglifescientist2018** [comment]
That was awesome

**Comment by Audrey-me** [comment]
added the background image and the last changes too

**Pull request merged**
